# permissions for end users to edit gsoc2secrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: gsoc2secret-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8-operator
    app.kubernetes.io/part-of: k8-operator
    app.kubernetes.io/managed-by: kustomize
  name: gsoc2secret-editor-role
rules:
- apiGroups:
  - secrets.gsoc2.com
  resources:
  - gsoc2secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets.gsoc2.com
  resources:
  - gsoc2secrets/status
  verbs:
  - get
